title:              Yang Jeong Park
email:              parkyj@kist.re.kr
description:        Computational Science Research Center, <br>Korea Institute of Science and Technology
author:             Yang Jeong Park
baseurl:            ""
url:                "https://parkyangjeong.github.io"

# Social Profiles
twitter_username:   
github_username:    parkyjmit
facebook_username:  
instagram_username:  
linkedin_username:   parkyj

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
